version: 2.1

orbs:
  fcheck: jimicircleci/fcheck@dev:alpha

jobs:
  clone_private_repo:
    docker:
      # - image: circleci/python:3.9
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Run docker commands
          command: |
            docker --version
            cat /etc/os-release
            docker run --rm --volume $PWD:/src shahidraza962/python-code-checks:2 black
            docker run --rm --volume $PWD:/src shahidraza962/python-code-checks:2 isort

      # - run:
      #     name: Clone Private Repo
      #     command: |
      #       mkdir privaterepo
      #       ls -la
      #       git config --global credential.helper store
      #       git clone https://$GITHUB_USERNAME:$PAT@github.com/$GITHUB_USERNAME/privaterepo.git privaterepo
      #       ls -al privaterepo

      # - fcheck/pip

      # - run:
      #     name: Run shell script
      #     command: |
      #       cd privaterepo
      #       chmod +x docker_miniconda_ubuntu_setup.sh
      #       echo running script...
      #       ./docker_miniconda_ubuntu_setup.sh

workflows:
  static-checks:
    jobs:
      # - fcheck/pip:
      #     context: static-checks
      - clone_private_repo
          # context:
          #   - github-cred
          #   - static-checks
          # requires:
          #  - fcheck/pip
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - fcheck/format:
          context: static-checks
      - fcheck/lint:
          context: static-checks
      - fcheck/mypy:
          context: static-checks
