version: 2.1

orbs:
  static-checks: jimicircleci/static-checks@0.0.1

jobs:
  my-job:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Calling the command from the private orb with arguments
      - static-checks/add:
          numA: 2
          numB: 6
# workflows:
#   test-calc:
#     jobs:
#       # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
#       # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
#       - test/add:
#           numA: 2
#           numB: 6
